// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO-lCe-wN4RUzBdaw0gYXk8XcRTRngB-Q',
    appId: '1:117330126935:web:8dd30c377b67939612db12',
    messagingSenderId: '117330126935',
    projectId: 'fir-9cf1b',
    authDomain: 'fir-9cf1b.firebaseapp.com',
    databaseURL: 'https://fir-9cf1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-9cf1b.appspot.com',
    measurementId: 'G-ZCHPFZE3TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7k42BudgqPEt0smzzyAqV5QhiLJtfQ7U',
    appId: '1:117330126935:android:eaf482569171f46512db12',
    messagingSenderId: '117330126935',
    projectId: 'fir-9cf1b',
    databaseURL: 'https://fir-9cf1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-9cf1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBziU7VA8KbzSQ5REJ5yTP6QVuoLZ8A3uU',
    appId: '1:117330126935:ios:4a93fdbcf1c4825412db12',
    messagingSenderId: '117330126935',
    projectId: 'fir-9cf1b',
    databaseURL: 'https://fir-9cf1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-9cf1b.appspot.com',
    iosClientId: '117330126935-ids8te26q9ijdu1rk0q0370cdeh16hoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBziU7VA8KbzSQ5REJ5yTP6QVuoLZ8A3uU',
    appId: '1:117330126935:ios:4a93fdbcf1c4825412db12',
    messagingSenderId: '117330126935',
    projectId: 'fir-9cf1b',
    databaseURL: 'https://fir-9cf1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-9cf1b.appspot.com',
    iosClientId: '117330126935-ids8te26q9ijdu1rk0q0370cdeh16hoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chessApp',
  );
}
